### PR TITLE
Fixed navigation issue in BlockNavigation component

### LINKED ISSUE #1154: New history is pushed on navigating back - BlockNavigation
Video : https://vimeo.com/715895274/f5b424c3f4

 Please check the below code for reference which handle the issue mentioned.
```
import React, { useState, useEffect, useRef } from "react";

import { Alert } from "neetoui";
import { useTranslation } from "react-i18next";
import { useHistory } from "react-router-dom";

const PageNavigateAlert = ({ when }) => {
  const { t } = useTranslation();
  const history = useHistory();

  const [showPrompt, setShowPrompt] = useState(false);
  const unblockRef = useRef();

  const handleUnblock = () => {
    if (showPrompt) {
      setShowPrompt(false);
      unblockRef.current?.();
    }
  };

  useEffect(() => {
    const unblock = history.block((transition, action) => {
      if (when) {
        setShowPrompt(true);
        unblockRef.current = () => {
          unblock();
          switch (action) {
            case "PUSH":
              history.push(transition);
              break;
            case "REPLACE":
              history.replace(transition);
              break;
            case "POP":
              history.goBack();
              break;
          }
        };
        return false;
      }

      return undefined;
    });

    return () => {
      unblock();
    };
  }, [when]);

  return (
    <div>
      <Alert
        title={t("common.pageNavigate.title")}
        message={t("common.pageNavigate.description")}
        isOpen={showPrompt}
        onClose={() => setShowPrompt(false)}
        onSubmit={handleUnblock}
      />
    </div>
  );
};

export default PageNavigateAlert;

```
cc: @labeebklatif

### PR DESCRIPTION
**Pull request by ajil-paul**
Fixes #1154 

**Description**

- Fixed: navigation issue in _BlockNavigation_ component

**Checklist**

- [x] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary label (patch/minor/major - If package publish is required)
- [x] I have followed the suggested description format and styling

@amaldinesh7 _a Please review

### CODE REVIEW

File: lib/components/formik/BlockNavigation.js [hunk 1]
```diff
@@ -1,27 +1,66 @@
...
 
+import Alert from "../Alert";
+
 const NavigationHandler = ({ isDirty = false }) => {
   const formikContext = useFormikContext();
   const shouldBlock =
     isDirty || (Boolean(formikContext) && Boolean(formikContext.dirty));
-  const { blocked, hidePrompt, navigate } = useNavPrompt({ shouldBlock });
+
+  const [showPrompt, setShowPrompt] = useState(false);
```
Comment (amaldinesh7) [inline lib/components/formik/BlockNavigation.js:13]: can you move the block navigation logic to a hook?

**Review by amaldinesh7 — CHANGES_REQUESTED** [review]
@ajil-paul _a Please check the comment.

**Comment by ajil-paul** [comment]
@amaldinesh7 _a Please review
