### PR TITLE
Fixed empty ref issue in `Table` component

### LINKED ISSUE #1795: Fix empty ref issue in Table component
Ref: https://github.com/bigbinary/neeto-invoice-web/issues/4426

The code was added in the following PR: https://github.com/bigbinary/neeto-ui/pull/1720

@ajmaln _a

cc: @praveen-murali-ind @anil-anand

### PR DESCRIPTION
**Pull request by adityamahajan-io**
- Fixes #1795 

**Description**
- Fixed: bug with sortable columns trying to access a `null` `headerRef ` in the `handleHeaderClasses` function. 
-  Achieved the same behavior of center aligning table header content for sortable columns, without depending on `headerRef` to do so.

**Checklist**
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] ~~I have made corresponding changes to the documentation~~
- [x] ~~I have updated the types definition of modified exports.~~
- [x] ~~I have added tests that prove my fix is effective or that my feature works.~~
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

@ajmaln _a Please review.

### CODE REVIEW

File: src/components/Table/index.jsx [hunk 1]
```diff
@@ -131,6 +124,15 @@ const Table = ({
...
   };
 
+  const sortedColumnsWithAlignment = sortedColumns.map(sortedColumn => ({
+    ...sortedColumn,
+    onHeaderCell: column => {
+      const col = column.onHeaderCell?.(sortedColumn);
+
+      return { ...col, "data-text-align": column.align };
+    },
+  }));
```
Comment (ajmaln) [inline src/components/Table/index.jsx:134]:
```suggestion
  const sortedColumnsWithAlignment = sortedColumns.map(sortedColumn => ({
    ...sortedColumn,
    onHeaderCell: column => {
      const col = sortedColumn.onHeaderCell?.(column);

      return { ...col, "data-text-align": column.align };
    },
  }));
```

**Review by ajmaln — COMMENTED** [review]
@adityamahajan-io _a

**Comment by adityamahajan-io** [comment]
@ajmaln _a Added the fix. Please have a look.

**Review by ajmaln — APPROVED** [review]
