### PR TITLE
Fixed an issue where getFromLocalStorage() could throw errors in environments where localStorage is inaccessible or null.

### LINKED ISSUE #2419: getFromLocalStorage() should be safe in instances where localStorage is not accessible
There are some browsers/contexts where `localStorage` seems to be null, `getFromLocalStorage()` should return the default value in such instances: https://app.honeybadger.io/projects/100611/faults/116883249

@josephmathew900 _a Please assign someone to work on this

### PR DESCRIPTION
**Pull request by MazahirHaroon**
- Fixes #2419 

**Description**

- Wrapped all localStorage operations in try-catch blocks to handle potential failures in private browsing mode or due to storage restrictions.

**Checklist**

- [ ] ~I have made corresponding changes to the documentation.~
- [ ] ~I have updated the types definition of modified exports.~
- [x] I have verified the functionality in some of the neeto web-apps.
- [ ] ~I have added tests that prove my fix is effective or that my feature works.~
- [ ] ~I have added proper `data-cy` and `data-testid` attributes.~
- [x] I have added the necessary label (`patch`/`minor`/`major` - If package publish
      is required).

**Reviewers**

@josephmathew900 _a
cc: @AbhayVAshokan

### CODE REVIEW

**Comment by MazahirHaroon** [comment]
@josephmathew900 I tested this in the NeetoCal application but couldn't reproduce the issue. Let me know if I should look further into it.

**Comment by MazahirHaroon** [comment]
@MazahirHaroon _a Assigning it back to me to verify if all the CI tests are passing.

**Comment by MazahirHaroon** [comment]
The CI tests have passed. @josephmathew900 _a

File: src/utils/index.js [hunk 1]
```diff
@@ -188,10 +188,17 @@ export const setToLocalStorage = (key, value) =>
 export const removeFromLocalStorage = key => localStorage.removeItem(key);
```
Comment (josephmathew900) [inline src/utils/index.js:188]: We also need to wrap `setToLocalStorage` and `removeFromLocalStorage` in `try-catch` blocks.

File: src/utils/index.js [hunk 2]
```diff
@@ -188,10 +188,17 @@ export const setToLocalStorage = (key, value) =>
...
-  // eslint-disable-next-line @bigbinary/neeto/no-local-storage
-  const storedValue = localStorage.getItem(key);
+  try {
+    // eslint-disable-next-line @bigbinary/neeto/no-local-storage
+    const storedValue = localStorage.getItem(key);
+
+    return storedValue ? JSON.parse(storedValue) : defaultValue;
+  } catch (error) {
+    // eslint-disable-next-line no-console
+    console.error(error);
```
Comment (josephmathew900) [inline src/utils/index.js:198]: We don't need to log the error to the console, silently return the default value.

**Review by josephmathew900 — COMMENTED** [review]
@MazahirHaroon _a

File: src/utils/index.js (hunk 2 above)
Comment (MazahirHaroon) [reply src/utils/index.js]: This is completed in https://github.com/bigbinary/neeto-ui/pull/2420/commits/d58872ceb89f4c0602724d113f3037f919cefb92.

File: src/utils/index.js (hunk 1 above)
Comment (MazahirHaroon) [reply src/utils/index.js]: It is handled in https://github.com/bigbinary/neeto-ui/pull/2420/commits/0551420b73ed4d44242e354e2204710a93d4299f but I do have a query, please watch this [NeetoRecord](https://mazahir-haroon.neetorecord.com/watch/f831789fc465755513c6).

Comment (josephmathew900) [reply src/utils/index.js]: @MazahirHaroon This is fine. We are using these storage functions in the `useLocalStorage` hook and the `useRecentlyUsedColors` hook, which already have in-memory logic. That means if `localStorage` is null, it won't break. Instead, it will store the data in memory and use it. But when we refresh, those data will be lost since we are not storing them in `localStorage` and that is fine.

**Comment by josephmathew900** [comment]
@MazahirHaroon _a
- Can you check if we can replace [getStorageValue](https://github.com/bigbinary/neeto-ui/blob/70cf3b70ce83c256380a866dc105a905a59c9da7/src/hooks/useLocalStorage.js#L9) in `useLocalStorage` hook  with `getFromLocalStorage` in our util?
- Update the issue description, now we have made changes to 3 localStorage functions.

**Comment by MazahirHaroon** [comment]
@josephmathew900 Yes, we can. The `getFromLocalStorage` was not present in our utils when [getStorageValue](https://github.com/bigbinary/neeto-ui/blob/70cf3b70ce83c256380a866dc105a905a59c9da7/src/hooks/useLocalStorage.js#L9) was added in this [commit](https://github.com/bigbinary/neeto-ui/pull/2310/commits/8219dd7c28deb19d84a6e6db7b4a66b1e1085c82). Now that we have a utils function, we can replace [getStorageValue](https://github.com/bigbinary/neeto-ui/blob/70cf3b70ce83c256380a866dc105a905a59c9da7/src/hooks/useLocalStorage.js#L9) with it to avoid duplication.

The change has been made in this [commit](https://github.com/bigbinary/neeto-ui/pull/2420/commits/07ca173a28e4a4b4b52509d2c85b1c476ccaf193).

**Review by josephmathew900 — APPROVED** [review]
LGTM
