### PR TITLE
Fixed scroll to error on enter key press

### LINKED ISSUE #1780: Enter key is not triggering scroll when `scrollToErrorField` is enabled
@Calvinwilson99 _a

### PR DESCRIPTION
**Pull request by Calvinwilson99**
- Fixes #1780 

**Description**
Fixed: scroll to error is not triggered on submitting form with enter key.

**Checklist**

- ~~[ ] I have made corresponding changes to the documentation.~~
- ~~[ ] I have updated the types definition of modified exports.~~
- [x] I have verified the functionality in some of the neeto web-apps.
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

### CODE REVIEW

**Comment by Calvinwilson99** [comment]
@ajmaln _a. Please review.

File: src/components/formik/Form/ScrollToErrorField/index.js [hunk 1]
```diff
@@ -16,18 +16,8 @@ const ScrollToErrorField = ({ formRef }) => {
     if (!formRef.current || isValidatedReference.current || isValid) return;
     isValidatedReference.current = true;
```
Comment (ajmaln) [inline src/components/formik/Form/ScrollToErrorField/index.js:17]: As discussed, let's remove this `ref` and the additional `useEffect`

**Comment by Calvinwilson99** [comment]
@ajmaln _a. Removed the unnecessary ref.

**Review by ajmaln — APPROVED** [review]
