### PR TITLE
Add data-cy for toastr and fix data-cy property undefined

### LINKED ISSUE #231: Add data-cy for toastr
@datt _a

### PR DESCRIPTION
**Pull request by datt**
Fixes #231.

### CODE REVIEW

**Comment by datt** [comment]
@edwinbbu _a Please review.

File: lib/components/Toastr.js [hunk 1]
```diff
@@ -1,6 +1,7 @@
 import React from "react";
 import * as R from "ramda";
 import { toast, Slide } from "react-toastify";
+import { hyphenize } from "../common";
```
Comment (edwinbbu) [inline lib/components/Toastr.js:4]: @datt _a This import is not used in the file. Please remove it. Rest looks good. 
Please make this change and the merge the PR. Thanks
