### PR TITLE
Fixed disabled time in date/time picker component

### LINKED ISSUE #1912: Styling for disabled time in date picker is not working
https://github.com/bigbinary/neeto-ui/assets/22771826/661f3d5a-b63c-49ce-9471-e058758a5390

@goutham-subramanyam _a

cc// @praveen-murali-ind

### PR DESCRIPTION
**Pull request by goutham-subramanyam**
- Fixes #1912 

**Description**

**Checklist**

- [ ] ~I have made corresponding changes to the documentation.~
- [ ] ~I have updated the types definition of modified exports.~
- [ ] ~I have verified the functionality in some of the neeto web-apps.~
- [ ] ~I have added tests that prove my fix is effective or that my feature works~
- [ ] ~I have added the necessary label (patch/minor/major - If package publish
      is required).~

**Reviewers**
@praveen-murali-ind _a Please review.

### CODE REVIEW

**Review by praveen-murali-ind — APPROVED** [review]
LGTM. @ajmaln _a Please review.

File: stories/Components/constants.js [hunk 1]
```diff
@@ -270,3 +270,17 @@ export const EVENT_BUBBLING_CAPTURING = `const EventBubblingAndCapturing = () =>
...
 };`;
 
+export const range = (start, end) => {
+  const result = [];
+  for (let i = start; i < end; i++) {
+    result.push(i);
+  }
+
+  return result;
+};
```
Comment (ajmaln) [inline stories/Components/constants.js]: `range` is available in `ramda`. We can use it

**Review by ajmaln — APPROVED** [review]

**Review by ajmaln — APPROVED** [review]
