### PR TITLE
Fixed janky animation in panes with forms containing `autoFocus`

### LINKED ISSUE #1396: Animations run incorrectly on element with autofocus input
Ref: https://github.com/bigbinary/neeto-planner-web/issues/2665

### PR DESCRIPTION
**Pull request by akkshaylawrence**
Fixes #1396 

**Description**
- Fixes janky animation in _Pane_ when form fields have the `autoFocus` prop.

**Checklist**

- [ ] ~~I have made corresponding changes to the documentation.~~
- [ ] ~~I have updated the types definition of modified exports.~~
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

### CODE REVIEW

**Comment by akkshaylawrence** [comment]
@amaldinesh7 please review.

**Comment by amaldinesh7** [comment]
@akkshaylawrence _a Please check the failing tests.

File: src/utils/index.js [hunk 1]
```diff
@@ -66,7 +66,7 @@ export const renderFocusOnFocusableElements = (
   shouldFocusFirstFocusableElement = true
 ) => {
   const focusableElements =
-    'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])';
```
Comment (amaldinesh7) [inline src/utils/index.js:69]: We can keep the button here. Let's not change the existing behavior.

**Review by amaldinesh7 — COMMENTED** [review]
@akkshaylawrence _a Please check the comment.

**Comment by amaldinesh7** [comment]
@akkshaylawrence Please check the delay in displaying content as we discussed.
