### PR TITLE
Fixed the z-index of fixed table column

### LINKED ISSUE #1878: Fix the z-index of fixed table column
Screenshot 2023-10-16 at 3 07 20 PM

@goutham-subramanyam _a

### PR DESCRIPTION
**Pull request by goutham-subramanyam**
- Fixes #1878 

**Description**

**Checklist**

- [x] ~I have made corresponding changes to the documentation.~
- [x] ~I have updated the types definition of modified exports.~
- [x] ~I have verified the functionality in some of the neeto web-apps.~
- [x] ~I have added tests that prove my fix is effective or that my feature works~
- [x] ~I have added the necessary label (patch/minor/major - If package publish
      is required).~

**Reviewers**

### CODE REVIEW

**Comment by goutham-subramanyam** [comment]
@praveen-murali-ind _a As discussed, please check and let me know which approach would be the best option.

File: src/components/Dropdown/index.jsx [hunk 1]
```diff
@@ -128,6 +126,7 @@ const Dropdown = ({
       role="dropdown"
       theme="light"
       trigger={isControlled ? undefined : TRIGGERS[trigger]}
+      zIndex={99999}
```
Comment (praveen-murali-ind) [inline src/components/Dropdown/index.jsx:129]: @goutham-subramanyam _a Let’s revert this change and proceed with the second approach of decreasing the table column z-index.

**Comment by goutham-subramanyam** [comment]
@ajmaln _a Please review.

cc: @praveen-murali-ind

**Review by ajmaln — APPROVED** [review]
