### PR TITLE
Fixed search not working with Select creatable

### LINKED ISSUE #1111: Select with isCreatable does not support searching
Refer: https://github.com/bigbinary/neeto-kb-web/issues/1340

image

In the above screenshot, there is one available option with label `JavaScript`.

### PR DESCRIPTION
**Pull request by mohit-s96**
closes #1111

### CODE REVIEW

**Comment by mohit-s96** [comment]
@karthiknmenon _a. Please review.

**Comment by mohit-s96** [comment]
@ajmaln _a. Please review.

File: lib/components/Select.js [hunk 1]
```diff
@@ -46,7 +47,14 @@ const Select = ({
...
   if (isCreateable) {
+    Parent = Creatable;
+  }
+
+  if (otherProps.loadOptions) {
     Parent = AsyncCreatable;
+  } else if (otherProps.defaultOptions) {
+    otherProps.options = otherProps.defaultOptions;
+    otherProps.defaultOptions = null;
   }
```
Comment (ajmaln) [inline lib/components/Select.js:58]: @mohit-s96 _a

As discussed, I think we should update the docs for `Creatable` to use only `options` prop instead. The `defaultOptions` could be a boolean or a list of options, so this could cause some bugs.

@amaldinesh7 LMK your thoughts

Comment (amaldinesh7) [reply lib/components/Select.js:58]: Yeah, we can update the stories to use `options` instead of `defaultOptions` and remove any code related to `defaultOptions` from select component

**Review by ajmaln — APPROVED** [review]
@amaldinesh7 _a Please review

**Comment by amaldinesh7** [comment]
@mohit-s96 _a Could you please check whether the tags molecule's unit tests are failing because of the change in the Select component?

Remove the other change from the changelog and keep version 3.4.2

**Comment by mohit-s96** [comment]
@amaldinesh7 _a. Please review the changes. The test was failing because `molecules/tags` was using `defaultOptions` instead of `options`.
