### PR TITLE
Fix issue in onBlur event in Select

### LINKED ISSUE #710: On blur event is not working on Formik Select component
The default onBlur action (mark the field as touched) is not executing.
https://www.loom.com/share/3911459a9da44719a57897f4b45c6180

### PR DESCRIPTION
**Pull request by AJIL-PAUL**
Fixes #710 

Change: Moved CustomInput to outside of Select component

cc @karthiknmenon

### CODE REVIEW

File: lib/components/Select.js [hunk 1]
```diff
@@ -11,6 +11,18 @@ const sizes = {
   large: "large",
 };
 
+// Refer: https://github.com/bigbinary/neeto-ui/issues/123
```
Comment (amaldinesh7) [inline lib/components/Select.js:14]: Please remove this comment.

File: lib/components/Select.js [hunk 2]
```diff
@@ -11,6 +11,18 @@ const sizes = {
...
+  const { selectProps } = props;
+  return (
+    <components.Input
+      {...props}
+      data-testid={selectProps && selectProps["data-testid"]}
+      data-cy={selectProps && selectProps["data-cy"]}
+    ></components.Input>
+  );
+};
+
```
Comment (amaldinesh7) [inline lib/components/Select.js:25]: Can you please give a brief on what was the cause of the issue and how this change will fix it?

**Review by amaldinesh7 — CHANGES_REQUESTED** [review]
@AJIL-PAUL _a Please take a look at the comments

File: lib/components/Select.js (hunk 2 above)
Comment (AJIL-PAUL) [reply lib/components/Select.js:24]: Issue:
- The onBlur callback was not triggered after selecting an option. So that the touched property in formik context would't get update.
- Initially the CustomInput component was defined inside the Parent component
- So when we click on the the select component and select an option, the selected value changes and this lead to re-render the Parent component
- This will lead re-creating the CustomInput and will cleanup the focus listener in it. So after choosing an option, if we click outside of the Select component, the onBlur callback will not be called.

Solution:
- Moved the definition  of  CustomInput component to outside of the Parent Component.
- This will avoid re-creating the CustomInput while Parent re-renders.
- So even if we select and option and clicked outside of the component, the onBlur will get triggered. 
- And the touched property in Formik context will also get updated.

**Review by amaldinesh7 — APPROVED** [review]
